FEATURES_ENGELEN_LATEST_OLD: list[str] = [
    'Dst Port', 
    'Protocol', 
    'Flow Duration', 
    'Total Fwd Packet', 
    'Total Bwd packets', 
    'Total Length of Fwd Packet', 
    'Total Length of Bwd Packet', 
    'Fwd Packet Length Max', 
    'Fwd Packet Length Min', 
    'Fwd Packet Length Mean', 
    'Fwd Packet Length Std', 
    'Bwd Packet Length Max', 
    'Bwd Packet Length Min', 
    'Bwd Packet Length Mean', 
    'Bwd Packet Length Std', 
    'Flow Bytes/s', 
    'Flow Packets/s', 
    'Flow IAT Mean', 
    'Flow IAT Std', 
    'Flow IAT Max', 
    'Flow IAT Min', 
    'Fwd IAT Total', 
    'Fwd IAT Mean', 
    'Fwd IAT Std', 
    'Fwd IAT Max', 
    'Fwd IAT Min', 
    'Bwd IAT Total', 
    'Bwd IAT Mean', 
    'Bwd IAT Std', 
    'Bwd IAT Max', 
    'Bwd IAT Min', 
    'Fwd PSH Flags', 
    'Bwd PSH Flags', 
    'Fwd URG Flags', 
    'Bwd URG Flags', 
    'Fwd RST Flags', 
    'Bwd RST Flags', 
    'Fwd Header Length', 
    'Bwd Header Length', 
    'Fwd Packets/s', 
    'Bwd Packets/s', 
    'Packet Length Min', 
    'Packet Length Max', 
    'Packet Length Mean', 
    'Packet Length Std',
    'Packet Length Variance',
    'FIN Flag Count', 
    'SYN Flag Count', 
    'RST Flag Count', 
    'PSH Flag Count', 
    'ACK Flag Count', 
    'URG Flag Count', 
    'CWR Flag Count', 
    'ECE Flag Count', 
    'Down/Up Ratio',
    'Average Packet Size',
    'Fwd Segment Size Avg',
    'Bwd Segment Size Avg', 
    'Fwd Bytes/Bulk Avg', 
    'Fwd Packet/Bulk Avg', 
    'Fwd Bulk Rate Avg', 
    'Bwd Bytes/Bulk Avg', 
    'Bwd Packet/Bulk Avg', 
    'Bwd Bulk Rate Avg', 
    'Subflow Fwd Packets', 
    'Subflow Fwd Bytes', 
    'Subflow Bwd Packets', 
    'Subflow Bwd Bytes', 
    'FWD Init Win Bytes', 
    'Bwd Init Win Bytes', 
    'Fwd Act Data Pkts', 
    'Bwd Act Data Pkts', 
    'Fwd Seg Size Min', 
    'Bwd Seg Size Min', 
    'Active Mean', 
    'Active Std', 
    'Active Max', 
    'Active Min', 
    'Idle Mean', 
    'Idle Std', 
    'Idle Max', 
    'Idle Min', 
    'ICMP Code', 
    'ICMP Type', 
    'Fwd TCP Retrans. Count', 
    'Bwd TCP Retrans. Count', 
    'Total TCP Retrans. Count', 
    'Total Connection Flow Time', 
]



FEATURES_ENGELEN_LATEST_NEW: list[str] = [
    'Dst Port',
    'Protocol',
    'Flow Duration',
    'Total Fwd Packet',
    'Total Bwd packets',
    'Fwd Segment Payload Length Total',
    'Bwd Segment Payload Length Total',
    'Fwd Segment Payload Length Max',
    'Fwd Segment Payload Length Min',
    'Fwd Segment Payload Length Mean',
    'Fwd Segment Payload Length Std',
    'Bwd Segment Payload Length Max',
    'Bwd Segment Payload Length Min',
    'Bwd Segment Payload Length Mean',
    'Bwd Segment Payload Length Std',
    'Flow Bytes/s',
    'Flow Packets/s',
    'Flow IAT Mean',
    'Flow IAT Std',
    'Flow IAT Max',
    'Flow IAT Min',
    'Fwd IAT Total',
    'Fwd IAT Mean',
    'Fwd IAT Std',
    'Fwd IAT Max',
    'Fwd IAT Min',
    'Bwd IAT Total',
    'Bwd IAT Mean',
    'Bwd IAT Std',
    'Bwd IAT Max',
    'Bwd IAT Min',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Fwd RST Flags',
    'Bwd RST Flags',
    'Fwd Header Length',
    'Bwd Header Length',
    'Fwd Packets/s',
    'Bwd Packets/s',
    'Segment Payload Length Min',
    'Segment Payload Length Max',
    'Segment Payload Length Mean',
    'Segment Payload Length Std',
    'Segment Payload Length Variance',
    'FIN Flag Count',
    'SYN Flag Count',
    'RST Flag Count',
    'PSH Flag Count',
    'ACK Flag Count',
    'URG Flag Count',
    'CWR Flag Count',
    'ECE Flag Count',
    'Down/Up Ratio',
    'Segment Payload Length Avg',
    'Fwd Segment Payload Length Avg',
    'Bwd Segment Payload Length Avg',
    'Fwd Bytes/Bulk Avg',
    'Fwd Packet/Bulk Avg',
    'Fwd Bulk Rate Avg',
    'Bwd Bytes/Bulk Avg',
    'Bwd Packet/Bulk Avg',
    'Bwd Bulk Rate Avg',
    'Subflow Fwd Packets',
    'Subflow Fwd Bytes',
    'Subflow Bwd Packets',
    'Subflow Bwd Bytes',
    'FWD Init Win Bytes',
    'Bwd Init Win Bytes',
    'Fwd Act Data Pkts',
    'Bwd Act Data Pkts',
    'Fwd Segment Header Length Min',
    'Bwd Segment Header Length Min',
    'Active Mean',
    'Active Std',
    'Active Max',
    'Active Min',
    'Idle Mean',
    'Idle Std',
    'Idle Max',
    'Idle Min',
    'ICMP Code',
    'ICMP Type',
    'Fwd TCP Retrans. Count',
    'Bwd TCP Retrans. Count',
    'Total TCP Retrans. Count',
    'Total Connection Flow Time',
]


MAP_ENGELEN_LATEST_NEW_OLD: dict[str, str] = {
    'Dst Port': 'Dst Port',
    'Protocol': 'Protocol',
    'Flow Duration': 'Flow Duration',
    'Total Fwd Packet': 'Total Fwd Packet',
    'Total Bwd packets': 'Total Bwd packets',
    'Fwd Segment Payload Length Total': 'Total Length of Fwd Packet',
    'Bwd Segment Payload Length Total': 'Total Length of Bwd Packet',
    'Fwd Segment Payload Length Max': 'Fwd Packet Length Max',
    'Fwd Segment Payload Length Min': 'Fwd Packet Length Min',
    'Fwd Segment Payload Length Mean': 'Fwd Packet Length Mean',
    'Fwd Segment Payload Length Std': 'Fwd Packet Length Std',
    'Bwd Segment Payload Length Max': 'Bwd Packet Length Max',
    'Bwd Segment Payload Length Min': 'Bwd Packet Length Min',
    'Bwd Segment Payload Length Mean': 'Bwd Packet Length Mean',
    'Bwd Segment Payload Length Std': 'Bwd Packet Length Std',
    'Flow Bytes/s': 'Flow Bytes/s',
    'Flow Packets/s': 'Flow Packets/s',
    'Flow IAT Mean': 'Flow IAT Mean',
    'Flow IAT Std': 'Flow IAT Std',
    'Flow IAT Max': 'Flow IAT Max',
    'Flow IAT Min': 'Flow IAT Min',
    'Fwd IAT Total': 'Fwd IAT Total',
    'Fwd IAT Mean': 'Fwd IAT Mean',
    'Fwd IAT Std': 'Fwd IAT Std',
    'Fwd IAT Max': 'Fwd IAT Max',
    'Fwd IAT Min': 'Fwd IAT Min',
    'Bwd IAT Total': 'Bwd IAT Total',
    'Bwd IAT Mean': 'Bwd IAT Mean',
    'Bwd IAT Std': 'Bwd IAT Std',
    'Bwd IAT Max': 'Bwd IAT Max',
    'Bwd IAT Min': 'Bwd IAT Min',
    'Fwd PSH Flags': 'Fwd PSH Flags',
    'Bwd PSH Flags': 'Bwd PSH Flags',
    'Fwd URG Flags': 'Fwd URG Flags',
    'Bwd URG Flags': 'Bwd URG Flags',
    'Fwd RST Flags': 'Fwd RST Flags',
    'Bwd RST Flags': 'Bwd RST Flags',
    'Fwd Header Length': 'Fwd Header Length',
    'Bwd Header Length': 'Bwd Header Length',
    'Fwd Packets/s': 'Fwd Packets/s',
    'Bwd Packets/s': 'Bwd Packets/s',
    'Segment Payload Length Min': 'Packet Length Min',
    'Segment Payload Length Max': 'Packet Length Max',
    'Segment Payload Length Mean': 'Packet Length Mean',
    'Segment Payload Length Std': 'Packet Length Std',
    'Segment Payload Length Variance': 'Packet Length Variance',
    'FIN Flag Count': 'FIN Flag Count',
    'SYN Flag Count': 'SYN Flag Count',
    'RST Flag Count': 'RST Flag Count',
    'PSH Flag Count': 'PSH Flag Count',
    'ACK Flag Count': 'ACK Flag Count',
    'URG Flag Count': 'URG Flag Count',
    'CWR Flag Count': 'CWR Flag Count',
    'ECE Flag Count': 'ECE Flag Count',
    'Down/Up Ratio': 'Down/Up Ratio',
    'Segment Payload Length Avg': 'Average Packet Size',
    'Fwd Segment Payload Length Avg': 'Fwd Segment Size Avg',
    'Bwd Segment Payload Length Avg': 'Bwd Segment Size Avg',
    'Fwd Bytes/Bulk Avg': 'Fwd Bytes/Bulk Avg',
    'Fwd Packet/Bulk Avg': 'Fwd Packet/Bulk Avg',
    'Fwd Bulk Rate Avg': 'Fwd Bulk Rate Avg',
    'Bwd Bytes/Bulk Avg': 'Bwd Bytes/Bulk Avg',
    'Bwd Packet/Bulk Avg': 'Bwd Packet/Bulk Avg',
    'Bwd Bulk Rate Avg': 'Bwd Bulk Rate Avg',
    'Subflow Fwd Packets': 'Subflow Fwd Packets',
    'Subflow Fwd Bytes': 'Subflow Fwd Bytes',
    'Subflow Bwd Packets': 'Subflow Bwd Packets',
    'Subflow Bwd Bytes': 'Subflow Bwd Bytes',
    'FWD Init Win Bytes': 'FWD Init Win Bytes',
    'Bwd Init Win Bytes': 'Bwd Init Win Bytes',
    'Fwd Act Data Pkts': 'Fwd Act Data Pkts',
    'Bwd Act Data Pkts': 'Bwd Act Data Pkts',
    'Fwd Segment Header Length Min': 'Fwd Seg Size Min',
    'Bwd Segment Header Length Min': 'Bwd Seg Size Min',
    'Active Mean': 'Active Mean',
    'Active Std': 'Active Std',
    'Active Max': 'Active Max',
    'Active Min': 'Active Min',
    'Idle Mean': 'Idle Mean',
    'Idle Std': 'Idle Std',
    'Idle Max': 'Idle Max',
    'Idle Min': 'Idle Min',
    'ICMP Code': 'ICMP Code',
    'ICMP Type': 'ICMP Type',
    'Fwd TCP Retrans. Count': 'Fwd TCP Retrans. Count',
    'Bwd TCP Retrans. Count': 'Bwd TCP Retrans. Count',
    'Total TCP Retrans. Count': 'Total TCP Retrans. Count',
    'Total Connection Flow Time': 'Total Connection Flow Time',

}


